/*
 * Copyright 2008-2026 Async-IO.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
import { test, expect } from '@playwright/test';

/**
 * E2E for rag-chat slash commands in the shipped console.
 *
 * REQUIRES: samples/spring-boot-rag-chat running KEYLESS on port 8080.
 *
 * The 4.0.60 release-gate found that `/sources` typed in the console went
 * straight to the LLM (the console connects to RagChatEndpoint, an
 * @AiEndpoint, and @Command was only honored on the @Agent path). The fix is
 * the AiHandlerDecorator SPI: @Command now routes on @AiEndpoint too. This
 * spec proves the end-to-end wire from the console:
 *  - `/sources` returns the instant KB listing (no LLM), and
 *  - a normal question still flows through RAG retrieval (the command router
 *    only intercepts `/`-prefixed messages).
 */

test.describe('rag-chat: slash commands on the @AiEndpoint console', () => {
  test('/sources is an instant command; plain questions still hit RAG', async ({ page, baseURL }) => {
    await page.goto(`${baseURL}/atmosphere/console/`);
    await expect(page.getByText('Connected', { exact: false }).first()).toBeVisible({ timeout: 15_000 });

    const input = page.getByRole('textbox');

    // /sources — routed by the command decorator BEFORE the model, so it is a
    // deterministic KB listing regardless of LLM availability.
    await input.fill('/sources');
    await input.press('Enter');
    await expect(page.getByText(/Knowledge Base \(\d+ documents\):/)).toBeVisible({ timeout: 15_000 });
    // A real KB document is listed — proves the command executed, not the LLM.
    await expect(page.getByText(/\.md \(\d+ words\)/).first()).toBeVisible();

    // /help — auto-generated by the command router, listing /sources.
    await input.fill('/help');
    await input.press('Enter');
    await expect(page.getByText('Available commands:')).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText('/sources').last()).toBeVisible();

    // A non-slash message must NOT be swallowed by the command router — it
    // flows through the RAG pipeline, which retrieves and injects context.
    // "Relevant context" only appears when the ContextProvider ran (the
    // streaming path), so it is the definitive proof the message was NOT
    // handled as a command. Deterministic keyless (DemoAgentRuntime echoes
    // the injected context).
    await input.fill('What transports does Atmosphere support?');
    await input.press('Enter');
    await expect(page.getByText(/Relevant context/i).first()).toBeVisible({ timeout: 30_000 });
  });
});
