/*
 * Copyright 2008-2026 Async-IO.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.atmosphere.spring.boot;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.aot.hint.MemberCategory;
import org.springframework.beans.factory.aot.BeanFactoryInitializationAotContribution;
import org.springframework.beans.factory.aot.BeanFactoryInitializationAotProcessor;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;

/**
 * Runs Atmosphere's annotation scan during Spring AOT processing and records the
 * result for the runtime to read.
 *
 * <p>AOT processing happens on a JVM with a real classpath, which is the last
 * moment a {@code .class} scan can succeed for a native image. The class names
 * are written to {@value AtmosphereAnnotationScanner#PRECOMPUTED_RESOURCE};
 * {@code AtmosphereAutoConfiguration} prefers that file over scanning, so the
 * native binary gets the same handler map the JVM would have built.</p>
 *
 * <p>Finding the classes is only half of it — the framework instantiates them
 * reflectively and reads their annotations, so each one is registered for
 * reflection here too. Without that the list would resolve and the handlers
 * would still fail to construct.</p>
 *
 * <p>This runs for every AOT build, including JVM-target ones. That is harmless:
 * the file simply matches what a runtime scan would have produced.</p>
 */
class AtmosphereAnnotationScanAotProcessor implements BeanFactoryInitializationAotProcessor {

    private static final Logger logger =
            LoggerFactory.getLogger(AtmosphereAnnotationScanAotProcessor.class);

    /**
     * Everything the framework does reflectively with a handler class:
     * construct it, invoke its annotated methods, and inject its fields.
     */
    private static final MemberCategory[] HANDLER_CATEGORIES = {
            MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
            MemberCategory.INVOKE_DECLARED_METHODS,
            MemberCategory.ACCESS_DECLARED_FIELDS
    };

    @Override
    public BeanFactoryInitializationAotContribution processAheadOfTime(
            ConfigurableListableBeanFactory beanFactory) {

        // The scan honours atmosphere.packages, so the same property the runtime
        // would have used has to be resolved here. Binding the full
        // AtmosphereProperties is not possible this early, and reading the raw
        // property keeps this to the one value that matters.
        var packages = resolvePackages(beanFactory);

        return (generationContext, beanFactoryInitializationCode) -> {
            var classes = AtmosphereAnnotationScanner.scan(packages);

            var body = new StringBuilder();
            body.append("# Generated by Atmosphere during Spring AOT processing.\n");
            body.append("# Classpath scanning cannot run in a native image, so the\n");
            body.append("# annotated classes are resolved here and read back at startup.\n");
            for (var clazz : classes) {
                body.append(clazz.getName()).append('\n');
            }

            generationContext.getGeneratedFiles().addResourceFile(
                    AtmosphereAnnotationScanner.PRECOMPUTED_RESOURCE, body.toString());

            var hints = generationContext.getRuntimeHints();
            hints.resources().registerPattern(AtmosphereAnnotationScanner.PRECOMPUTED_RESOURCE);
            for (var clazz : classes) {
                hints.reflection().registerType(clazz, HANDLER_CATEGORIES);
            }

            // Atmosphere annotations name collaborators by class literal —
            // @Message(encoders = …, decoders = …) most visibly, but also
            // broadcasters, filters and interceptors. Those are instantiated
            // reflectively too, and registering only the annotated class leaves
            // them out: the handler registers, then dies with "Unable to load
            // encoder class" the moment a message arrives. Collected from the
            // annotation attributes themselves rather than an enumerated list,
            // so an extension adding its own Class-valued attribute is covered.
            var collaborators = collaboratorTypes(classes);
            for (var clazz : collaborators) {
                hints.reflection().registerType(clazz, HANDLER_CATEGORIES);
            }

            logger.info("Atmosphere recorded {} annotated class(es) and {} referenced "
                            + "encoder/decoder/collaborator type(s) for ahead-of-time startup",
                    classes.size(), collaborators.size());
        };
    }

    /**
     * Every type named by a class literal inside an Atmosphere annotation on the
     * given classes — encoders, decoders, broadcasters, filters, interceptors.
     *
     * <p>Both class-level and method-level annotations are walked, because
     * {@code @Message} sits on a method while {@code @ManagedService} sits on the
     * type. Reading the attribute values instead of naming known attributes keeps
     * this correct when a module introduces its own.</p>
     */
    private java.util.Set<Class<?>> collaboratorTypes(java.util.Set<Class<?>> classes) {
        var found = new java.util.LinkedHashSet<Class<?>>();
        for (var clazz : classes) {
            for (var annotation : clazz.getAnnotations()) {
                collectFrom(annotation, found);
            }
            for (var method : clazz.getDeclaredMethods()) {
                boolean annotated = false;
                for (var annotation : method.getAnnotations()) {
                    collectFrom(annotation, found);
                    annotated |= isAtmosphereAnnotation(annotation.annotationType());
                }
                // The payload types of an annotated method. @Message names its
                // encoder and decoder by class literal — those are picked up
                // above — but the DTO they convert appears only as this method's
                // parameter and return type. Jackson reflects over that DTO's
                // constructor and fields, so registering the codec without the
                // type it encodes gets as far as invoking the codec and then
                // fails on the payload.
                if (annotated) {
                    for (var parameter : method.getParameterTypes()) {
                        addPayloadType(parameter, found);
                    }
                    addPayloadType(method.getReturnType(), found);
                }
            }
        }
        found.removeAll(classes);
        return found;
    }

    /** Whether an annotation is one of Atmosphere's own. */
    private boolean isAtmosphereAnnotation(Class<? extends java.lang.annotation.Annotation> type) {
        return type.getName().startsWith("org.atmosphere.");
    }

    /**
     * Register a payload type, skipping what cannot need a hint.
     *
     * <p>Primitives and {@code void} have no reflective surface. Framework and JDK
     * types are either already registered or supplied by the image. What remains is
     * the application's own DTOs — the types a codec actually has to construct and
     * populate.</p>
     */
    private void addPayloadType(Class<?> type, java.util.Set<Class<?>> sink) {
        if (type == null || type.isPrimitive() || type.isArray() || type.isInterface()) {
            return;
        }
        // Only JDK types are skipped. Filtering out "org.atmosphere.*" as framework
        // types looks right and is wrong: the samples live under
        // org.atmosphere.samples.*, so that filter silently dropped the very DTOs
        // this method exists to register. Framework types that slip through are
        // already registered via the metadata SPI, and re-registering one costs
        // image size — while missing one costs a silent runtime failure.
        var name = type.getName();
        if (name.startsWith("java.") || name.startsWith("javax.")
                || name.startsWith("jakarta.")) {
            return;
        }
        sink.add(type);
    }

    private void collectFrom(java.lang.annotation.Annotation annotation,
                             java.util.Set<Class<?>> sink) {
        for (var attribute : annotation.annotationType().getDeclaredMethods()) {
            if (attribute.getParameterCount() != 0) {
                continue;
            }
            var type = attribute.getReturnType();
            if (!Class.class.equals(type)
                    && !(type.isArray() && Class.class.equals(type.getComponentType()))) {
                continue;
            }
            try {
                var value = attribute.invoke(annotation);
                if (value instanceof Class<?> single) {
                    sink.add(single);
                } else if (value instanceof Class<?>[] many) {
                    java.util.Collections.addAll(sink, many);
                }
            } catch (ReflectiveOperationException | RuntimeException e) {
                // A default referencing a type absent from this build. Skipping is
                // right: it cannot be needed at run time either, and failing the
                // AOT build over an unused default would be worse than the gap.
                logger.debug("Could not read {}.{} while collecting Atmosphere "
                                + "collaborator types", annotation.annotationType().getName(),
                        attribute.getName(), e);
            }
        }
    }

    /**
     * Read {@code atmosphere.packages} from the environment backing this build.
     *
     * @return the configured packages, or {@code null} when unset — the scan
     *         still covers the framework's own packages in that case
     */
    private String resolvePackages(ConfigurableListableBeanFactory beanFactory) {
        try {
            var environment = beanFactory.getBean(org.springframework.core.env.Environment.class);
            return environment.getProperty("atmosphere.packages");
        } catch (org.springframework.beans.BeansException e) {
            logger.debug("No Environment available during AOT processing; "
                    + "scanning framework packages only", e);
            return null;
        }
    }
}
