/*
 * Copyright 2008-2026 Async-IO.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.atmosphere.ai.tool;

import java.util.Map;

/**
 * Executes an AI tool with the given arguments and returns a result.
 *
 * <p>Implementations are typically generated by reflection from
 * {@link org.atmosphere.ai.annotation.AiTool}-annotated methods, but can
 * also be created manually for dynamic tool registration.</p>
 */
@FunctionalInterface
public interface ToolExecutor {

    /**
     * Execute the tool.
     *
     * @param arguments the tool arguments as provided by the AI model,
     *                  keyed by parameter name
     * @return the result (will be serialized to JSON and sent back to the model)
     * @throws Exception if tool execution fails
     */
    Object execute(Map<String, Object> arguments) throws Exception;
}
