#!/usr/bin/env bash
#
# Copyright 2008-2026 Async-IO.org
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
# ABOUTME: carnet — file, claim, release, label and close issues in the private register
# ABOUTME: A claim records who holds an issue and which Claude Code session, so a peer session sees it first
#
# The register is the tracker named by registre.toml (`tracker = "owner/repo"`), overridable
# with REGISTRE_TRACKER — the same key and variable the limitation gates in .registre read.
# Nothing here names a tracker: a checkout without registre.toml has no register. The script
# must stay portable: macOS bash 3.2 (no associative arrays, no mapfile, no ${var,,}), BSD
# sed, jq, gh.
#
# A claim is three native GitHub facts that move together:
#   assignee            = the human accountable (gh login)
#   label  in-progress  = a live session holds the issue
#   newest marker line  = which session — an HTML comment carrying one JSON object:
#       <!-- carnet-claim {"v":1,"session":"<uuid>","name":"…","user":"…","host":"…","pid":N,"repo":"…","branch":"…","at":"…"} -->
#       <!-- carnet-release {…,"reason":"…"} -->
# `status` reads the newest marker; the label and assignee are the list-view mirrors of it.
set -euo pipefail
# Everything written here is this account's alone: the ledger, the gh login and the prompt
# hook's status cache, which holds the private tracker's issue titles. A shared host's default
# umask would leave them readable by every other local user.
umask 077

MARKER_VERSION=1
CLAIM_LABEL="in-progress"
DRY_RUN=0

# ------------------------------------------------------------------ output helpers
say()  { printf '%s\n' "$*"; }
warn() { printf '⚠️  %s\n' "$*" >&2; }
die()  { printf '❌ %s\n' "$1" >&2; exit "${2:-1}"; }
need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required (brew install $1)"; }
now()  { date -u +%Y-%m-%dT%H:%M:%SZ; }

# Every mutating gh call goes through run(), so --dry-run shows exactly what would change.
run() {
    if [ "$DRY_RUN" = 1 ]; then
        printf '[dry-run] %s\n' "$*" >&2
        return 0
    fi
    "$@"
}

# ------------------------------------------------------------------ tracker transport
# `gh issue`, `gh pr` and `gh repo view` are GraphQL. A cloud session's agent proxy serves
# only a pinned set of PR-review GraphQL operations and refuses every other query with a 403
# naming this REST fallback, so those subcommands fail there against EVERY repository —
# including the one attached to the session, and regardless of any token supplied. REST works
# in both places, so the tracker is reached exclusively through `gh api`.
api() { gh api "$@"; }

# Label names travel in the URL path on delete, so encode rather than trust the convention.
uri() { jq -rn --arg s "$1" '$s|@uri'; }

# Every entry is written by a Claude session, so a "Generated by/with Claude Code" footer or a
# Co-Authored-By trailer says nothing and costs tokens on every later read. Each body is
# stripped of those lines, then of the blank and `---` lines they leave dangling at the end.
UNSIGNED='def unsigned: split("\n")
    | map(select(test("^\\s*_?(🤖\\s*)?Generated (with|by) \\[?Claude Code"; "i")
                 or test("^\\s*Co-Authored-By:\\s*Claude"; "i") | not))
    | until(length == 0 or (last | test("^\\s*(-{3,})?\\s*$") | not); .[:-1])
    | join("\n") + "\n";'

# Temp files live in one directory per run ($SCRATCH, made in main), removed on every exit:
# a claim that dies half-way — a 5xx on the comment POST — must not leave its payload and marker
# body behind in $TMPDIR. Subshells reset the EXIT trap, so only the script's own exit clears it.
tmpfile() { mktemp "$SCRATCH/carnet.XXXXXX"; }

# The body reaches the API as JSON built by jq, never as a shell argument, so backticks,
# quotes and newlines in a marker comment cannot corrupt the request.
api_comment() { # <n> <body-file>
    local payload
    payload=$(tmpfile)
    jq -n --rawfile b "$2" "$UNSIGNED"'{body:($b|unsigned)}' > "$payload"
    run api "repos/$TRACKER/issues/$1/comments" -X POST --input "$payload" >/dev/null
    rm -f "$payload"
}

api_assign()    { run api "repos/$TRACKER/issues/$1/assignees" -X POST   -f "assignees[]=$2" >/dev/null; }
api_unassign()  { run api "repos/$TRACKER/issues/$1/assignees" -X DELETE -f "assignees[]=$2" >/dev/null; }
api_label_add() { run api "repos/$TRACKER/issues/$1/labels"    -X POST   -f "labels[]=$2"    >/dev/null; }
# Removing a label the issue does not carry answers 404. `gh issue edit --remove-label`
# tolerated that, and release/close both call this unconditionally, so it stays tolerated.
# Nothing else is: a 5xx, a 403 or a rate limit returns 1 with gh's error, and each caller
# stops there — before a release marker and a dropped ledger line would claim the label went.
api_label_rm() {
    local path err
    path="repos/$TRACKER/issues/$1/labels/$(uri "$2")"
    if [ "$DRY_RUN" = 1 ]; then run api "$path" -X DELETE; return 0; fi
    err=$(api "$path" -X DELETE 2>&1 >/dev/null) && return 0
    case $err in *"(HTTP 404)"*) return 0 ;; esac
    printf '%s\n' "$err" >&2
    return 1
}

usage() {
    cat <<'EOF'
carnet — the private register, from the command line

  carnet.sh claim   <n> [--steal]                 hold carnet#n: assign me, label in-progress, marker comment
  carnet.sh release <n> [--reason <why>]          let go of carnet#n (inverse of claim)
  carnet.sh release --all [--reason <why>] [--session <uuid>]
                                                   release everything this session (or <uuid>) still holds,
                                                   in every register its ledger names
  carnet.sh status  [<n>] [--short]               who holds carnet#n — or every in-progress issue
  carnet.sh mine    [--verify]                    what this session holds, from its local ledger
  carnet.sh create  --title <t> [--label <l>]... (--body <b> | --body-file <f> | stdin) [--claim]
                                                   file an issue: "[<project>] <t>", project label, private tracker
  carnet.sh close   <n> --why <text> [--commit <sha>]
                                                   close with a mandatory reason and the commit that resolved it
  carnet.sh label   <n> +<label> -<label> ...     add / remove labels
  carnet.sh tracker                               print the tracker this checkout files into

  --dry-run   print the gh commands that would mutate the tracker instead of running them

Exit codes: 0 done · 1 error · 2 refused (held by another live session, or on another host)
EOF
}

# ------------------------------------------------------------------ repo + tracker
need gh
need jq
need git

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || die "run this inside a git checkout"

TRACKER=${REGISTRE_TRACKER:-}
if [ -z "$TRACKER" ]; then
    [ -f "$REPO_ROOT/registre.toml" ] || die "no registre.toml at $REPO_ROOT — this repo names no register (see .registre/README.md)"
    TRACKER=$(sed -n 's/^tracker[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$REPO_ROOT/registre.toml" | head -1)
fi
[ -n "$TRACKER" ] || die "registre.toml has no tracker key"
# The tracker is spliced into every API path, so anything but a bare owner/repo is refused
# before it reaches one.
[[ $TRACKER =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || die "tracker must be owner/repo, got: $TRACKER"
CHECKOUT_TRACKER=$TRACKER

# The repo name comes from origin, never from the checkout's basename: a worktree is named
# after its branch or its agent (.claude/worktrees/agent-…), which is not a project.
ORIGIN_URL=$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || true)
ORIGIN_SLUG=$(printf '%s' "$ORIGIN_URL" | sed -E 's#^(git@github\.com:|https://github\.com/|ssh://git@github\.com/)##; s#\.git$##; s#/$##')
REPO_NAME=${ORIGIN_SLUG##*/}
[ -n "$REPO_NAME" ] || REPO_NAME=$(basename "$REPO_ROOT")
# The title prefix and the project label are the repo name itself: Atmosphere/atmosphere
# files "[atmosphere] …" under the `atmosphere` label.
PROJECT=$REPO_NAME
BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)
BRANCH=${BRANCH//--/-}

# ------------------------------------------------------------------ session identity
# Claude Code exports the session id and its own pid; the per-process file under the config
# dir carries the name set by /rename (or the derived one). Outside Claude Code the claim is
# a manual one: it still records the human, and nothing auto-releases it.
CFG=${CLAUDE_CONFIG_DIR:-$HOME/.claude}
LEDGER_DIR="$CFG/carnet-claims"
# The umask covers what this run creates, not a tree an older copy of these scripts left at
# 0755 — mkdir -p never changes an existing directory's mode. At 0700 the top of the tree cuts
# off everything below it, whoever wrote it.
[ ! -d "$LEDGER_DIR" ] || chmod 700 "$LEDGER_DIR" 2>/dev/null || true
SESSION_ID=${CLAUDE_CODE_SESSION_ID:-}
SESSION_PID=${CLAUDE_PID:-}
HOST=$(hostname -s 2>/dev/null || hostname)
NAME=""
USER_LOGIN=""
SHORT_ID=""

session_name() {
    local f="$CFG/sessions/${SESSION_PID:-none}.json" n=""
    if [ -n "$SESSION_PID" ] && [ -f "$f" ]; then
        n=$(jq -r --arg sid "$SESSION_ID" 'select(.sessionId == $sid) | .name // empty' "$f" 2>/dev/null || true)
    fi
    [ -n "$n" ] || n=${SESSION_ID:0:8}
    [ -n "$n" ] || n="shell"
    # "--" would end the HTML comment the marker lives in.
    printf '%s' "${n//--/-}"
}

gh_login() {
    local cache="$LEDGER_DIR/gh-login" login
    if [ -f "$cache" ] && [ -n "$(find "$cache" -mmin -1440 2>/dev/null)" ]; then
        cat "$cache"
        return 0
    fi
    login=$(gh api user -q .login 2>/dev/null) || die "gh api user failed — run: gh auth login"
    mkdir -p "$LEDGER_DIR"
    printf '%s' "$login" > "$cache"
    printf '%s' "$login"
}

load_identity() {
    NAME=$(session_name)
    USER_LOGIN=$(gh_login)
    SHORT_ID=${SESSION_ID:0:8}
    [ -n "$SHORT_ID" ] || SHORT_ID=manual
}

identity_json() {
    jq -cn \
        --arg v "$MARKER_VERSION" --arg session "${SESSION_ID:-manual}" --arg name "$NAME" \
        --arg user "$USER_LOGIN" --arg host "$HOST" --arg pid "${SESSION_PID:-$$}" \
        --arg repo "$REPO_NAME" --arg branch "$BRANCH" --arg at "$(now)" \
        '{v:($v|tonumber), session:$session, name:$name, user:$user, host:$host,
          pid:($pid|tonumber), repo:$repo, branch:$branch, at:$at}'
}

# Whether a claim marker names the caller. A Claude Code session is its id. Every caller outside
# Claude Code records the same session, "manual", so a manual marker is the caller's only when it
# also names the caller's gh login: otherwise any two shells — two people, or a person and a
# non-Claude agent — would each read the other's claim as their own, then release or close it.
held_by_me() { # <holder-json>
    [ "$(jq -r .session <<<"$1")" = "${SESSION_ID:-manual}" ] || return 1
    [ -n "$SESSION_ID" ] || [ "$(jq -r .user <<<"$1")" = "$USER_LOGIN" ]
}

# ------------------------------------------------------------------ local ledger
# One JSON-lines file per session: line 1 is the identity, then one line per held issue.
# The SessionEnd hook reads it to release what the session still holds; `mine` reads it
# without a single API call. Every line names its tracker, so one config dir can serve
# checkouts that file into different registers.
ledger_file() { [ -n "$SESSION_ID" ] && printf '%s' "$LEDGER_DIR/$SESSION_ID.jsonl"; }

# Every change to a ledger is an append or a read-modify-write, and subagents inherit their
# session's id — so its ledger. Two of them closing issues at once would each rewrite the file
# from the copy they read, and the second rename would bring back the line the first dropped.
# The lock is a directory beside the ledger (<id>.jsonl.lock, which no *.jsonl reader lists):
# mkdir is atomic everywhere, and flock does not exist on macOS. No update takes anywhere near
# ten seconds, so a lock that old was left by a holder killed inside one, and is broken.
ledger_lock() { # <ledger-file>
    local d="$1.lock" i=0
    mkdir -p "$LEDGER_DIR"
    until mkdir "$d" 2>/dev/null; do
        i=$((i + 1))
        if [ "$i" -ge 200 ]; then rmdir "$d" 2>/dev/null || true; i=0; fi
        sleep 0.05
    done
}
ledger_unlock() { rmdir "$1.lock" 2>/dev/null || true; }

# The identity line, written once, under the lock: two first appends must not each write it.
ledger_init() { # <ledger-file>
    [ -s "$1" ] || identity_json | jq -c '. + {kind:"identity"}' > "$1"
}

# Drops this tracker's <kind> line for issue n. The caller holds the lock.
ledger_filter() { # <ledger-file> <n> <kind>
    local tmp
    tmp=$(tmpfile) || return 1
    jq -c --arg t "$TRACKER" --argjson n "$2" --arg k "$3" \
        'select((.kind == $k and .tracker == $t and .issue == $n) | not)' "$1" > "$tmp" \
        && mv "$tmp" "$1"
}

# Every function below returns the failure rather than exiting inside the lock, so a jq error
# never strands it; the callers' errexit still stops them on that status.
ledger_append() { # <kind> <n>
    local f rc=0
    f=$(ledger_file) || return 0
    ledger_lock "$f"
    ledger_init "$f" \
        && jq -cn --arg k "$1" --arg t "$TRACKER" --argjson n "$2" --arg at "$(now)" \
               '{kind:$k, tracker:$t, issue:$n, at:$at}' >> "$f" \
        || rc=1
    ledger_unlock "$f"
    return $rc
}

ledger_add() { ledger_append claim "$1"; }

# Filed, not claimed. The tracker cannot say which session filed an issue, so the ledger
# records it, for an end-of-session audit to ask, per issue, why it is residue rather than the
# work the session was asked to do. That audit is bilan (check_carnet_filed in
# .agents/skills/bilan/bilan.sh), which caps the session at 6 while such an issue stays open;
# within this skill the lines also keep the ledger alive while they exist (ledger_drop).
ledger_filed() { ledger_append filed "$1"; }

# Labelled `limitation` by this session. A filed issue that is a registered limitation — the
# label plus a LIMITATION(registre#n) marker in source — is not residue, and an audit that
# reads the ledger offline, never touching the network, can only see the label through this
# line. `off` drops it when the label is removed.
ledger_limitation() { # <n> <on|off>
    local f rc=0
    f=$(ledger_file) || return 0
    ledger_lock "$f"
    ledger_init "$f" \
        && ledger_filter "$f" "$1" limitation \
        && { [ "$2" = off ] || jq -cn --arg t "$TRACKER" --argjson n "$1" --arg at "$(now)" \
                 '{kind:"limitation", tracker:$t, issue:$n, at:$at}' >> "$f"; } \
        || rc=1
    ledger_unlock "$f"
    return $rc
}

# Closing an issue this session filed clears its "filed" line: an issue opened and fixed in
# the same session is not residue, so the record of it has to end when the fix lands.
ledger_drop_filed() {
    local f rc=0
    f=$(ledger_file) || return 0
    [ -f "$f" ] || return 0
    ledger_lock "$f"
    [ ! -f "$f" ] || ledger_filter "$f" "$1" filed || rc=1
    ledger_unlock "$f"
    return $rc
}

ledger_drop() {
    local f rc=0
    f=$(ledger_file) || return 0
    [ -f "$f" ] || return 0
    ledger_lock "$f"
    if [ -f "$f" ]; then
        ledger_filter "$f" "$1" claim || rc=1
        # A ledger holding only its identity line is finished. "filed" lines count: they outlive
        # the claims on purpose, so the end of the session can still see them.
        if [ $rc = 0 ] && [ "$(jq -c 'select(.kind == "claim" or .kind == "filed")' "$f" | wc -l | tr -d ' ')" = 0 ]; then rm -f "$f"; fi
    fi
    ledger_unlock "$f"
    return $rc
}

ledger_issues() { # <file>
    [ -f "$1" ] || return 0
    jq -r --arg t "$TRACKER" 'select(.kind == "claim" and .tracker == $t) | .issue' "$1"
}

ledger_has() {
    local f
    f=$(ledger_file) || return 1
    ledger_issues "$f" | grep -qx "$1"
}

# ------------------------------------------------------------------ tracker reads
# REST names the field `html_url` and lower-cases the state, while three call sites below
# compare `.state` to "OPEN". Normalise here so those consumers are untouched by the
# transport change — a silent lower-case would make every claim die as "already closed".
#
# Only a 404 means the issue does not exist. A 5xx, a rate limit or an expired login say nothing
# about the issue, and the auto-claim hook retries those later but not a missing issue.
issue_json() {
    local raw errf
    errf=$(tmpfile)
    raw=$(api "repos/$TRACKER/issues/$1" 2>"$errf") || {
        grep -q '(HTTP 404)' "$errf" && die "carnet#$1 does not exist in $TRACKER"
        die "cannot read carnet#$1 from $TRACKER: $(grep -v '^$' "$errf" | tail -1)"
    }
    jq -c '{number, title, url: .html_url, state: (.state | ascii_upcase), labels, assignees}' <<<"$raw"
}

# Newest marker comment on the issue, or nothing. Claims and releases share one stream, so the
# last one wins.
#
# A stream that could not be read in full is a failure (return 1), never "no marker": gh prints
# the pages it got before one fails, so an older marker — or none — would pass for the newest,
# and claim, close and release would each act over a holder they could not see. Every caller
# dies on it, explicitly: `release --all` runs each release in a subshell, and a die inside the
# command substitution alone would only end that substitution.
last_marker() {
    local out
    out=$(api "repos/$TRACKER/issues/$1/comments" --paginate -q '.[].body' 2>/dev/null) || return 1
    printf '%s\n' "$out" | grep -oE '<!-- carnet-(claim|release) \{.*\} -->' | tail -1 || true
}
UNREADABLE="refusing to decide who holds it without reading every marker"
marker_kind() { local k=${1#<!-- carnet-}; printf '%s' "${k%% *}"; }
marker_json() { local j=${1#<!-- carnet-* }; printf '%s' "${j% -->}"; }

# 0 = that session is running on this host · 1 = it ended · 2 = another host, unknowable here.
# Claude Code removes sessions/<pid>.json on exit, so "file with matching id + live pid" is alive.
holder_alive() { # <host> <pid> <session>
    [ "$1" = "$HOST" ] || return 2
    local f
    for f in "$CFG/sessions/$2.json" "$HOME"/.claude*/sessions/"$2".json; do
        [ -f "$f" ] || continue
        [ "$(jq -r '.sessionId // empty' "$f" 2>/dev/null)" = "$3" ] || continue
        kill -0 "$2" 2>/dev/null && return 0
    done
    return 1
}

has_label() { jq -e --arg l "$2" '.labels[]? | select(.name == $l)' >/dev/null 2>&1 <<<"$1"; }

# The newest marker is another session's claim, and release or close was asked for. Exit 2 means
# what the usage says: that session may still be working it — running on this host, or on one
# whose liveness this host cannot see. A holder whose session ENDED is refused with 1 instead: a
# plain `claim` takes a stale claim over, so --steal (the user's call) is never the answer to it.
refuse_foreign() { # <n> <holder-json> <release|close>
    local n=$1 verb=$3 hs hn hu hh hp st
    hs=$(jq -r .session <<<"$2"); hn=$(jq -r .name <<<"$2"); hu=$(jq -r .user <<<"$2")
    hh=$(jq -r .host <<<"$2");    hp=$(jq -r .pid <<<"$2")
    if holder_alive "$hh" "$hp" "$hs"; then st=0; else st=$?; fi
    case $st in
        1) die "carnet#$n is held by ended session $hn (${hs:0:8}) of @$hu — 'claim $n' takes the stale claim over, then $verb" 1 ;;
        0) die "carnet#$n is held by @$hu · session $hn (${hs:0:8}), still running — not this session's to $verb; taking it over ('claim $n --steal') is your user's call" 2 ;;
        *) die "carnet#$n is held by @$hu · session $hn (${hs:0:8}) on host $hh, whose liveness cannot be checked from $HOST — not this session's to $verb; taking it over ('claim $n --steal') is your user's call" 2 ;;
    esac
}

# ------------------------------------------------------------------ claim
cmd_claim() { # <n> <steal>
    local n=$1 steal=$2 issue marker holder extra="" prev_user="" st
    issue=$(issue_json "$n")
    [ "$(jq -r .state <<<"$issue")" = "OPEN" ] || die "carnet#$n is closed — nothing to claim"

    marker=$(last_marker "$n") || die "cannot read the comments of carnet#$n — $UNREADABLE"
    if [ -n "$marker" ] && [ "$(marker_kind "$marker")" = claim ]; then
        holder=$(marker_json "$marker")
        local hs hn hu hh hp ha
        hs=$(jq -r .session <<<"$holder"); hn=$(jq -r .name <<<"$holder"); hu=$(jq -r .user <<<"$holder")
        hh=$(jq -r .host <<<"$holder");    hp=$(jq -r .pid <<<"$holder");  ha=$(jq -r .at <<<"$holder")
        if held_by_me "$holder"; then
            say "🔒 carnet#$n is already held by this session ($NAME)"
            return 0
        fi
        if holder_alive "$hh" "$hp" "$hs"; then st=0; else st=$?; fi
        case $st in
            0)  [ "$steal" = 1 ] || die "carnet#$n is held by @$hu · session $hn (${hs:0:8}) on $hh, still running since $ha. Re-run with --steal to take it over." 2
                warn "stealing carnet#$n from live session $hn (${hs:0:8}) of @$hu"
                extra="⚠️ Stolen from live session **$hn** (\`${hs:0:8}\`) of @$hu, held since $ha — that session no longer owns this issue." ;;
            1)  extra="♻️ Took over from ended session **$hn** (\`${hs:0:8}\`) of @$hu, held since $ha." ;;
            2)  [ "$steal" = 1 ] || die "carnet#$n is held by @$hu · session $hn (${hs:0:8}) on host $hh since $ha — liveness cannot be checked from $HOST. Re-run with --steal to take it over." 2
                warn "stealing carnet#$n from session $hn (${hs:0:8}) of @$hu on $hh"
                extra="⚠️ Stolen from session **$hn** (\`${hs:0:8}\`) of @$hu on $hh, held since $ha — that session no longer owns this issue." ;;
        esac
        prev_user=$hu
    fi

    local body
    body=$(tmpfile)
    {
        printf '<!-- carnet-claim %s -->\n' "$(identity_json)"
        printf '🔒 Claimed by @%s · session **%s** (`%s`) on %s · `%s` @ `%s` · %s\n' \
            "$USER_LOGIN" "$NAME" "$SHORT_ID" "$HOST" "$REPO_NAME" "$BRANCH" "$(now)"
        [ -z "$extra" ] || printf '\n%s\n' "$extra"
    } > "$body"

    # Recorded BEFORE the first write. A claim that dies part-way — a 5xx on the comment POST,
    # a hook timeout — has already assigned and labelled; with its line in the ledger, `release`
    # and the SessionEnd hook can take back what landed, where a line written last would leave
    # an assignee and a label that nothing could release. A retried claim adds no second line.
    [ "$DRY_RUN" = 1 ] || ledger_has "$n" || ledger_add "$n"
    if [ -n "$prev_user" ] && [ "$prev_user" != "$USER_LOGIN" ]; then
        api_unassign "$n" "$prev_user"
    fi
    api_assign "$n" "$USER_LOGIN"
    api_label_add "$n" "$CLAIM_LABEL"
    api_comment "$n" "$body"
    rm -f "$body"
    say "🔒 carnet#$n claimed by @$USER_LOGIN · session $NAME ($SHORT_ID) · $(jq -r .title <<<"$issue")"
}

# ------------------------------------------------------------------ release
release_comment() { # <reason> [extra lines...]
    local reason=$1; shift
    printf '<!-- carnet-release %s -->\n' "$(identity_json | jq -c --arg r "$reason" '. + {reason:$r}')"
    printf '🔓 Released by @%s · session **%s** (`%s`) · %s\n' "$USER_LOGIN" "$NAME" "$SHORT_ID" "$reason"
    local line
    for line in "$@"; do printf '%s\n' "$line"; done
}

# carnet#n in this checkout's register, owner/repo#n in another one: `release --all` walks every
# register a session's ledger names.
issue_ref() { if [ "$TRACKER" = "$CHECKOUT_TRACKER" ]; then printf 'carnet#%s' "$1"; else printf '%s#%s' "$TRACKER" "$1"; fi; }

cmd_release() { # <n> <reason>
    local n=$1 reason=${2:-done} marker holder held_by_me=0
    marker=$(last_marker "$n") || die "cannot read the comments of $(issue_ref "$n") — $UNREADABLE"
    if [ -n "$marker" ] && [ "$(marker_kind "$marker")" = claim ]; then
        holder=$(marker_json "$marker")
        if held_by_me "$holder"; then
            held_by_me=1
        elif ledger_has "$n"; then
            # Displaced: another session claimed it after this one did — a --steal, or a claim
            # race this one lost. The label and the assignee are the new holder's now, so nothing
            # is posted; what goes is this session's own record of a claim it no longer holds.
            [ "$DRY_RUN" = 1 ] || ledger_drop "$n"
            say "↪ $(issue_ref "$n") was taken over by @$(jq -r .user <<<"$holder") · session $(jq -r .name <<<"$holder") — this session no longer holds it: dropped from its ledger, nothing posted"
            return 0
        else
            refuse_foreign "$n" "$holder" release
        fi
    fi
    if [ $held_by_me = 0 ] && ! ledger_has "$n"; then
        die "carnet#$n is not held by this session — nothing to release"
    fi

    local body
    body=$(tmpfile)
    release_comment "$reason" > "$body"
    api_label_rm "$n" "$CLAIM_LABEL" \
        || die "$(issue_ref "$n"): could not remove the $CLAIM_LABEL label — not released, the claim stands"
    api_unassign "$n" "$USER_LOGIN"
    api_comment "$n" "$body"
    rm -f "$body"
    [ "$DRY_RUN" = 1 ] || ledger_drop "$n"
    say "🔓 $(issue_ref "$n") released ($reason)"
}

cmd_release_all() { # <reason> <session-or-empty>
    local reason=${1:-done} sid=$2 f row t n st rc=0
    if [ -n "$sid" ]; then
        # The SessionEnd hook path: the session's own process file may already be gone, so the
        # identity comes from the ledger it wrote when it claimed.
        f="$LEDGER_DIR/$sid.jsonl"
        [ -s "$f" ] || { say "session ${sid:0:8} holds nothing"; return 0; }
        local id
        id=$(head -1 "$f")
        SESSION_ID=$sid
        NAME=$(jq -r .name <<<"$id"); USER_LOGIN=$(jq -r .user <<<"$id"); SHORT_ID=${sid:0:8}
        SESSION_PID=$(jq -r .pid <<<"$id")
    else
        f=$(ledger_file) || { say "not inside a Claude Code session — nothing to release"; return 0; }
        [ -s "$f" ] || { say "this session holds nothing"; return 0; }
    fi
    # Every claim line, each under the register it names: one ledger serves every checkout the
    # session claimed from, and releasing only this checkout's register would leave the others
    # holding an assignee, a label and a claim marker for good.
    #
    # Each release runs in a subshell: die() exits the shell it is in, and one refused issue
    # must not stop the others from being released. Errexit is switched back on inside it: a
    # subshell on the left of || runs with errexit ignored, and a failed gh call would then be
    # reported as released and dropped from the ledger — unlike the same `release <n>` run alone.
    for row in $(jq -r --arg d "$TRACKER" 'select(.kind == "claim") | "\(.tracker // $d)|\(.issue)"' "$f" | sort -u); do
        t=${row%%|*}; n=${row#*|}
        if ! [[ $t =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ && $n =~ ^[0-9]+$ ]]; then
            rc=1; warn "the ledger names a malformed claim: $row"; continue
        fi
        set +e
        ( set -e; TRACKER=$t; cmd_release "$n" "$reason" )
        st=$?
        set -e
        [ "$st" = 0 ] || { rc=1; warn "$(TRACKER=$t; issue_ref "$n") was not released"; }
    done
    return $rc
}

# ------------------------------------------------------------------ close
cmd_close() { # <n> <why> <commit>
    local n=$1 why=$2 commit=$3 issue marker holder commit_url=""
    [ -n "$why" ] || die "close needs --why \"<what resolved it>\" — a close without a reason is invisible debt"
    issue=$(issue_json "$n")
    [ "$(jq -r .state <<<"$issue")" = "OPEN" ] || die "carnet#$n is already closed"

    if [ -n "$commit" ]; then
        git -C "$REPO_ROOT" cat-file -e "$commit^{commit}" 2>/dev/null \
            || die "commit $commit is not in this repository (worktrees share objects, so a typo is the likely cause)"
        commit_url="https://github.com/$ORIGIN_SLUG/commit/$(git -C "$REPO_ROOT" rev-parse "$commit")"
    fi

    marker=$(last_marker "$n") || die "cannot read the comments of carnet#$n — $UNREADABLE"
    if [ -n "$marker" ] && [ "$(marker_kind "$marker")" = claim ]; then
        holder=$(marker_json "$marker")
        if ! held_by_me "$holder"; then
            # Still listed in this session's ledger, it was taken from this session: that record
            # goes whatever the answer, since the close is refused — the issue is not its to close.
            if [ "$DRY_RUN" != 1 ] && ledger_has "$n"; then ledger_drop "$n"; fi
            refuse_foreign "$n" "$holder" close
        fi
    fi

    local body
    body=$(tmpfile)
    {
        printf '<!-- carnet-release %s -->\n' "$(identity_json | jq -c '. + {reason:"closed"}')"
        printf '✅ Closed by @%s · session **%s** (`%s`) · `%s` @ `%s`\n\n' "$USER_LOGIN" "$NAME" "$SHORT_ID" "$REPO_NAME" "$BRANCH"
        printf '**Why:** %s\n' "$why"
        [ -z "$commit_url" ] || printf '\n**Commit:** %s\n' "$commit_url"
    } > "$body"
    if has_label "$issue" "$CLAIM_LABEL" || [ "$(jq '.assignees | length' <<<"$issue")" != 0 ]; then
        api_label_rm "$n" "$CLAIM_LABEL" \
            || die "carnet#$n: could not remove the $CLAIM_LABEL label — not closed"
        api_unassign "$n" "$USER_LOGIN"
    fi
    api_comment "$n" "$body"
    run api "repos/$TRACKER/issues/$n" -X PATCH -f state=closed >/dev/null
    rm -f "$body"
    # A dry run closed nothing, so it leaves the ledger — claim and "filed" line alike — as it was.
    [ "$DRY_RUN" = 1 ] || { ledger_drop "$n"; ledger_drop_filed "$n"; }
    say "✅ carnet#$n closed · $(jq -r .title <<<"$issue")"
}

# ------------------------------------------------------------------ create
cmd_create() { # <title> <body> <body_file> <claim> labels...
    local title=$1 body=$2 body_file=$3 claim=$4; shift 4
    [ -n "$title" ] || die "create needs --title"

    # The whole point of a private register: an entry states where a defence is incomplete.
    local private
    private=$(api "repos/$TRACKER" -q .private 2>/dev/null || echo unknown)
    [ "$private" = true ] || die "tracker $TRACKER is not private (isPrivate=$private) — refusing to file"

    case "$title" in
        "["*) ;;
        *) title="[$PROJECT] $title" ;;
    esac

    local bf
    bf=$(tmpfile)
    if [ -n "$body_file" ]; then
        [ -f "$body_file" ] || die "no such body file: $body_file"
        cat "$body_file" > "$bf"
    elif [ -n "$body" ]; then
        printf '%s\n' "$body" > "$bf"
    elif [ ! -t 0 ]; then
        cat > "$bf"
    fi
    [ -s "$bf" ] || die "create needs a body: where it is (file + symbol), what is incomplete, what the fix looks like"

    local l has_limitation=0 labels=("$REPO_NAME")
    for l in "$@"; do
        [ "$l" = "$REPO_NAME" ] && continue
        labels+=("$l")
        [ "$l" = limitation ] && has_limitation=1
    done

    local payload
    payload=$(tmpfile)
    jq -n --arg t "$title" --rawfile b "$bf" --args \
        "$UNSIGNED"'{title:$t, body:($b|unsigned), labels:$ARGS.positional}' "${labels[@]}" > "$payload"

    local url n
    if [ "$DRY_RUN" = 1 ]; then
        run api "repos/$TRACKER/issues" -X POST --input "$payload"
        url="https://github.com/$TRACKER/issues/0"
    else
        url=$(api "repos/$TRACKER/issues" -X POST --input "$payload" -q .html_url) \
            || die "issue create failed"
    fi
    rm -f "$bf" "$payload"
    n=${url##*/}
    [ "$DRY_RUN" = 1 ] || [ "$n" = 0 ] || ledger_filed "$n"
    [ "$DRY_RUN" = 1 ] || [ "$n" = 0 ] || [ $has_limitation = 0 ] || ledger_limitation "$n" on
    say "📝 $url"
    say "   $title"
    [ $has_limitation = 0 ] || say "   marker: LIMITATION(registre#$n): <name the limited item on this line>"
    [ "$claim" = 1 ] && [ "$n" != 0 ] && cmd_claim "$n" 0
    return 0
}

# ------------------------------------------------------------------ label
cmd_label() { # <n> [+label|-label|label]...
    local n=$1; shift
    [ $# -gt 0 ] || die "label needs at least one +label or -label"
    local a
    for a in "$@"; do
        case "$a" in
            -*) api_label_rm  "$n" "${a#-}" || die "carnet#$n: could not remove the ${a#-} label"
                [ "$DRY_RUN" = 1 ] || [ "${a#-}" != limitation ] || ledger_limitation "$n" off ;;
            +*) api_label_add "$n" "${a#+}"
                [ "$DRY_RUN" = 1 ] || [ "${a#+}" != limitation ] || ledger_limitation "$n" on ;;
            *)  api_label_add "$n" "$a"
                [ "$DRY_RUN" = 1 ] || [ "$a" != limitation ] || ledger_limitation "$n" on ;;
        esac
    done
    say "🏷  carnet#$n: $*"
}

# ------------------------------------------------------------------ status
status_line() { # <n> <short>
    local n=$1 short=$2 issue marker holder title state line="" hint=""
    issue=$(issue_json "$n")
    title=$(jq -r .title <<<"$issue"); state=$(jq -r .state <<<"$issue")

    if [ "$state" != OPEN ]; then
        line="carnet#$n · closed"
    else
        # Unreadable is not unclaimed: an "open · unclaimed" line would send a reader, and the
        # prompt hook's shared cache, to work an issue whose holder nobody could see.
        marker=$(last_marker "$n") || die "cannot read the comments of carnet#$n — its holder is unknown, not absent"
        if [ -n "$marker" ] && [ "$(marker_kind "$marker")" = claim ]; then
            holder=$(marker_json "$marker")
            local hs hn hu hh hp ha hb live
            hs=$(jq -r .session <<<"$holder"); hn=$(jq -r .name <<<"$holder"); hu=$(jq -r .user <<<"$holder")
            hh=$(jq -r .host <<<"$holder");    hp=$(jq -r .pid <<<"$holder");  ha=$(jq -r .at <<<"$holder")
            hb=$(jq -r .branch <<<"$holder")
            if held_by_me "$holder"; then
                line="carnet#$n · held by THIS session ($hn) · $hb · since $ha"
            else
                if holder_alive "$hh" "$hp" "$hs"; then live="running"; else
                    case $? in 1) live="session ended — stale, 'claim $n' takes it over" ;; *) live="other host" ;; esac
                fi
                line="carnet#$n · held by @$hu · session $hn (${hs:0:8}) on $hh [$live] · $hb · since $ha"
            fi
            has_label "$issue" "$CLAIM_LABEL" || line="$line · (label missing)"
        else
            line="carnet#$n · open · unclaimed"
            has_label "$issue" "$CLAIM_LABEL" && line="$line · (stale in-progress label, no claim marker)"
            hint="claim before the first edit: .agents/skills/carnet/carnet.sh claim $n"
        fi
    fi

    if [ "$short" = 1 ]; then
        say "$line · $title"
    else
        say "$line"
        say "   $title"
        say "   $(jq -r .url <<<"$issue")"
        [ -z "$hint" ] || say "   → $hint"
    fi
}

cmd_status_all() {
    local nums n
    nums=$(api "repos/$TRACKER/issues?labels=$(uri "$CLAIM_LABEL")&state=open&per_page=100" \
        -q '.[] | select(.pull_request == null) | .number' 2>/dev/null) \
        || die "issue list failed"
    [ -n "$nums" ] || { say "no issue in $TRACKER is in progress"; return 0; }
    for n in $nums; do status_line "$n" 1; done
}

# Claims held under a DIFFERENT session id by this same user and host.
#
# A resumed session gets a new id and therefore a new, empty ledger, so `mine`
# answered "holds nothing" while the previous incarnation's claims sat in its own
# file — a false all-clear, and precisely when someone is auditing. Reported, but
# never as "yours": the other ledgers on this machine belong to LIVE PEERS as
# often as to a dead predecessor, and silently adopting a peer's claim would be a
# worse bug than the one this fixes. The tracker settles it — `status <n>` marks a
# gone holder `[session ended — stale]`.
mine_elsewhere() {
    local other id ident who claims any=0
    # No login known (none cached, none in this session's ledger): no ledger is "an earlier me".
    [ -n "$USER_LOGIN" ] || return 0
    for other in "$LEDGER_DIR"/*.jsonl; do
        [ -f "$other" ] || continue
        id=$(basename "$other" .jsonl)
        [ "$id" = "${SESSION_ID:-}" ] && continue
        ident=$(head -1 "$other" 2>/dev/null) || continue
        # Same person, same machine, or it is not a candidate for "an earlier me".
        [ "$(printf '%s' "$ident" | jq -r '.user // empty' 2>/dev/null)" = "$USER_LOGIN" ] || continue
        [ "$(printf '%s' "$ident" | jq -r '.host // empty' 2>/dev/null)" = "$HOST" ] || continue
        claims=$(ledger_issues "$other" | paste -sd, - 2>/dev/null)
        [ -n "$claims" ] || continue
        who=$(printf '%s' "$ident" | jq -r '.name // "unknown"' 2>/dev/null)
        [ "$any" = 0 ] && say "" && say "other session ids on this machine still list claims:"
        any=1
        say "  $who (${id:0:8}): $claims"
    done
    [ "$any" = 1 ] || return 0
    say ""
    say "  These are NOT necessarily yours — a live peer's ledger looks the same."
    say "  If one was an earlier incarnation of this session, its claims are"
    say "  invisible to \`mine\`. Settle each with: carnet.sh status <n>"
}

cmd_mine() { # <verify>
    local f n
    f=$(ledger_file) || die "not inside a Claude Code session"
    if [ -s "$f" ]; then
        say "session $NAME ($SHORT_ID) holds:"
        for n in $(ledger_issues "$f"); do
            if [ "$1" = 1 ]; then status_line "$n" 1; else
                say "  carnet#$n · since $(jq -r --arg t "$TRACKER" --argjson n "$n" 'select(.kind == "claim" and .tracker == $t and .issue == $n) | .at' "$f")"
            fi
        done
    else
        say "this session ($NAME) holds nothing"
    fi
    mine_elsewhere
}

# ------------------------------------------------------------------ main
sub=${1:-help}
[ $# -gt 0 ] && shift

case "$sub" in
    help|-h|--help) usage; exit 0 ;;
    # No identity and no API call: the prompt hook keys its status cache by this, because one
    # config dir serves every checkout on the machine and their registers' numbers overlap.
    tracker) say "$TRACKER"; exit 0 ;;
esac

SCRATCH=$(mktemp -d "${TMPDIR:-/tmp}/carnet.XXXXXX") || die "cannot create a temp directory"
trap 'rm -rf "$SCRATCH"' EXIT

case "$sub" in
    label)
        [ $# -ge 1 ] || die "label needs an issue number"
        n=$1; shift
        [[ $n =~ ^[0-9]+$ ]] || die "not an issue number: $n"
        # "-bug" is a label to remove, not a flag, so this subcommand keeps its own arguments.
        rest=()
        for a in "$@"; do
            if [ "$a" = --dry-run ]; then DRY_RUN=1; else rest+=("$a"); fi
        done
        load_identity
        cmd_label "$n" ${rest[@]+"${rest[@]}"}
        exit 0 ;;
esac

steal=0 reason="" session="" all=0 why="" commit="" title="" body="" body_file="" claim=0 short=0 verify=0
labels=()
positional=()
while [ $# -gt 0 ]; do
    case "$1" in
        --steal)     steal=1 ;;
        --dry-run)   DRY_RUN=1 ;;
        --all)       all=1 ;;
        --claim)     claim=1 ;;
        --short)     short=1 ;;
        --verify)    verify=1 ;;
        --reason)    reason=${2:-}; shift ;;
        --session)   session=${2:-}; shift ;;
        --why)       why=${2:-}; shift ;;
        --commit)    commit=${2:-}; shift ;;
        --title)     title=${2:-}; shift ;;
        --body)      body=${2:-}; shift ;;
        --body-file) body_file=${2:-}; shift ;;
        --label)     labels+=("${2:-}"); shift ;;
        -h|--help)   usage; exit 0 ;;
        -*)          die "unknown flag: $1 (see: carnet.sh help)" ;;
        *)           positional+=("$1") ;;
    esac
    shift
done

issue_arg() {
    local n=${positional[0]:-}
    [ -n "$n" ] || die "$sub needs an issue number"
    [[ $n =~ ^[0-9]+$ ]] || die "not an issue number: $n"
    printf '%s' "$n"
}

# `mine` is the offline audit, and it has to answer exactly when the tracker cannot: a logged-out
# gh would otherwise stop it at the login lookup, before the ledger is read. The login is only
# needed to recognise "an earlier me" in other ledgers, so the cached one serves at any age, and
# this session's own identity line after it. --verify asks the tracker, so it needs gh anyway.
if [ "$sub" = mine ] && [ "$verify" = 0 ]; then
    NAME=$(session_name)
    SHORT_ID=${SESSION_ID:0:8}
    [ -n "$SHORT_ID" ] || SHORT_ID=manual
    USER_LOGIN=$(cat "$LEDGER_DIR/gh-login" 2>/dev/null || true)
    [ -n "$USER_LOGIN" ] || USER_LOGIN=$(head -1 "$(ledger_file || true)" 2>/dev/null | jq -r '.user // empty' 2>/dev/null || true)
else
    load_identity
fi

case "$sub" in
    claim)   cmd_claim "$(issue_arg)" "$steal" ;;
    release)
        if [ "$all" = 1 ]; then cmd_release_all "${reason:-done}" "$session"
        else cmd_release "$(issue_arg)" "${reason:-done}"; fi ;;
    close)   cmd_close "$(issue_arg)" "$why" "$commit" ;;
    create)  cmd_create "$title" "$body" "$body_file" "$claim" ${labels[@]+"${labels[@]}"} ;;
    status)
        if [ -n "${positional[0]:-}" ]; then status_line "$(issue_arg)" "$short"
        else cmd_status_all; fi ;;
    mine)    cmd_mine "$verify" ;;
    *)       die "unknown subcommand: $sub (see: carnet.sh help)" ;;
esac
